[audio]
rate = 48000
period_size = 256
periods = 4 #4 periods in a buffer, so buffer size is 1024 samples
format = S16_LE

[speakers]

[reference_mics] #section
0 = hw:CARD=0,DEV=0 #key = value, can nest them

[error_mics]